### ISSUE TITLE
Issue with creating docx file on Mac using .net core 2.0 (corrupted docx file) 

### ISSUE THREAD

**Issue by danijela-k** [OfficeDev/Open-XML-SDK#249]
I am trying to use DocumentFormat.OpenXml on Mac (& .NETcore 2.0.0) to create docx file. 
Simple code like this ends up with unusable(corrupted) document:

```
 public void CreateDocx(String path)
        {

            using (WordprocessingDocument wordDocument =
                   WordprocessingDocument.Create(path, WordprocessingDocumentType.Document))
            {
                MainDocumentPart mainPart = wordDocument.AddMainDocumentPart();
                mainPart.Document = new DocumentFormat.OpenXml.Wordprocessing.Document();
                Body body = mainPart.Document.AppendChild(new Body());
                Paragraph para = body.AppendChild(new Paragraph());
                Run run = para.AppendChild(new Run());
                run.AppendChild(new Text("Create text in body - CreateWordprocessingDocument"));
            }
        }
```

I can load existing file and append some text in it, no problem there. But, creating new docx results with corrupted file. 
When I unzip docx and compare it with the unzipped docx file I can read with standard editors, I see that there are many files missing in my created docx (even though I am not sure if all of those are needed). 

I have tried version 2.7.2 and 2.8 with the same results. 
I am using OSX 10.12.6 (Sierra), Visual Studio 2017 for Mac, .NETcore 2.0.0

**Comment by tarunchopra** [comment]
@danijela-k : Thx for reporting the issue. I'll test it on MAC and investigate.

PS- Tested your code on windows and it's working fine.

**Comment by danijela-k** [comment]
Thanks for quick response. Looks like there is a problem in the _rels/.rels hidden file with the paths. 
Paths defined like this results in a good docx: 
`<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>`

but path defined like this creates truble (there is a slash before 'word'): 
`<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="/word/document.xml"/>`

When I manually remove that slash and re-zip the package -> docx opens as expected.

**Comment by tarunchopra** [comment]
@danijela-k : Thanks for the update. Sorry for the delay, will try to look into it over the weekend. Your inputs will help me.

**Comment by Depechie** [comment]
I have the same issue with Excel file being generated in Xamarin with .Net Standard 2.0

**Comment by Depechie** [comment]
Ha when I add the Environment.SetEnvironmentVariable("MONO_URI_DOTNETRELATIVEORABSOLUTE", "true"); line in the method where I create the excel AND in the method where I read out the created excel, everything works as expected.

**Comment by tarunchopra** [comment]
To confirm; setting the environment variable resolves the issue?

**Comment by Depechie** [comment]
Yes... I stubbed out several methods, one for creating the excel spreadsheet and one for inserting header row, etc...
I need to add the environment variable in each of them to get things working.

**Comment by twsouthwick** [comment]
Looks like we have a few options we could implement in our code: www.mono-project.com/docs/faq/known-issues/urikind-relativeorabsolute/.

**Comment by Depechie** [comment]
For reference here a current working version with Xamarin Forms [https://github.com/Depechie/XamarinFormsOffice](https://github.com/Depechie/XamarinFormsOffice)

**Comment by twsouthwick** [comment]
@Depechie can you try the fix in #267? I'm having trouble right now getting a Xamarin app to deploy... I'll try again tomorrow.

**Comment by Depechie** [comment]
@twsouthwick only now see this mention... is the check still needed? And if so, what is the easiest way to do so? Is there a preview Nuget feed for the OpenXML package?

**Comment by twsouthwick** [comment]
Yes, if you could try it out that would be great (I'm still having trouble getting Xamarin to deploy and attach debugger). The easiest way to try it out would be:

1. Download the nupkg from the artifacts tab on AppVeyor (see here: https://ci.appveyor.com/project/tomjebo/open-xml-sdk/build/2.7.3-PullRequest0267.41.build.260/artifacts)
2. Add it to a folder for a local nuget feed.
3. Add the local nuget feed to VS (see https://docs.microsoft.com/en-us/nuget/hosting-packages/local-feeds)
4. Replace your version with this one (you'll need to enable pre-release on the VS Nuget UI)

Thanks!

**Comment by Depechie** [comment]
This is possible with VS for Mac?

**Comment by Depechie** [comment]
Ok was able to get my VS2017 on Windows up to date!
So after adding the local nupkg from the artifacts tab in your link, I added the preview of the new OpenXML sdk ( 2.7.3 pullrequest0267-0041).

With following line of code in place : `Environment.SetEnvironmentVariable("MONO_URI_DOTNETRELATIVEORABSOLUTE", "true");` the app is working fine.
With this line of code in comment I get following exception :

> PackageRelationship target must be relative URI if TargetMode is Internal.
> Parameter name: targetUri

**Comment by twsouthwick** [comment]
Thanks for taking a look. VS for Mac should have some way of doing it, I'm just not familiar with that application. Looks like the fix isn't complete, then; we don't want to have to set the environment variable. It's fine as a work around, but will affect all libraries being run. I'll see if I can get my emulator working so I can try it out.

**Comment by twsouthwick** [comment]
@Depechie got Xamarin working, and it looks like the original issue is fixed (ie the package creation is working). However, System.IO.Packaging also has a usage of `UriKind.RelativeOrAbsolute` that needs to be addressed. See https://github.com/dotnet/corefx/issues/24822 for details

**Comment by Depechie** [comment]
Ha, good catch!!

**Comment by twsouthwick** [comment]
For now, we'll need to use the Environment variable work around until a fix from CoreFx is available

**Comment by twsouthwick** [comment]
I've merged the fix for creating files, but the environment variable is still needed to read the file.

**Comment by SanatMistry** [comment]
Hi @tarunchopra,
I am facing a similar problem wherein the docx file created using open XML does not open in MacOS. 

I have set the environment variable as well.  `Environment.SetEnvironmentVariable("MONO_URI_DOTNETRELATIVEORABSOLUTE", "true");` This does not solve my problem. I still get extra '/' in my target attribute.
